name: Publish to PyPI

on:
  release:
    types:
      - published

permissions:
  contents: read

jobs:
  publish:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    # - name: Install dependencies
    #   run: pip install setuptools==80.7.1 wheel==0.45.1 uv==0.7.5

    - name: Install uv
      run: pip install uv==0.7.5

    - name: Install build backend
      run:  uv pip install setuptools==80.7.1 wheel==0.45.1

    - name: Build the project
      run: uv build

    - name: Publish to PyPI
      run: uv publish --index pypi
      env:
        UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
